name: Lint HTML File

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint-html:
    name: Run HTMLLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Validate index.html
        run: htmlhint index.html
